[general]
connection = "Data Source=./App/bin/Debug/net6.0/WorkBotDatabase.sqlite3;Version=3;"
output = "./Infrastructure/HydraGenerated.fs"
namespace = "WorkTelegram.HydraGenerated"
cli_mutable = true
[readers]
reader_type = "System.Data.Common.DbDataReader"
[filters]
include = []
exclude = []
